### ISSUE TITLE
Hitting a snag after configuring this one

### ISSUE THREAD

**Issue by xhemp** [muppet3000/growatt-weather-based-charger#2]
Greetings,

Great job on this one ( I am also using the ha-growatt-server-api one, looks very promising (even though I have an SPA)! 
Just wondering what I could be doing wrong on this one.
I have configureed everyhing to the best of my knowledge but I can't get it to run at all.
This is what I get:

```
2023-03-04 11:45:42 ERROR: Caught an exception, oh dear....
2023-03-04 11:45:42 ERROR: Please check your configuration values also e.g. you've updated the default values
2023-03-04 11:45:42 ERROR: 'NoneType' object is not subscriptable
2023-03-04 11:45:42 INFO: Sleeping for 10 seconds before retry
```

It tries 3 times and then bails out.
Anything I can do get a bit more verbosity? :)

Thanks!

**Comment by xhemp** [comment]
Tried it just using the scripts (no docker) but it's the same, not sure where it's failing, though.

**Comment by muppet3000** [comment]
Hi xhemp, sorry for not responding the other day, I'm away this weekend, back tomorrow so unable to properly look at anything or help out.
I'll take a look when I'm back tomorrow. It could be an authentication problem but that would be odd.
I'm not sure I have much more logging in the code but I'm sure we can work it out between us!

**Comment by xhemp** [comment]
> Hi xhemp, sorry for not responding the other day, I'm away this weekend, back tomorrow so unable to properly look at anything or help out. I'll take a look when I'm back tomorrow. It could be an authentication problem but that would be odd. I'm not sure I have much more logging in the code but I'm sure we can work it out between us!

Hi muppet3000, no problems at all, there's no rush on this, take your time and again, thanks for your work on this and the growatt HA's plugin!

**Comment by muppet3000** [comment]
Hi @xhemp I've had a look through the code and I did a terrible job of implementing this error output :P

There's one of two problems here, either:
1. It's the fact you have an SPA inverter and this has only ever been tested with an SPH inverter (and I honestly don't know the difference), does yours show as "hybrid" in the server.growatt.com website??
or
2. It's a silly error in the configuration file

Would you be able to share your config file (remove any username & password information and I'll sub it out for my own and test it). That would at least allow us to rule out option 2.

If it's option 1 though I'm not sure how much help I'd be. I'd have to do some digging and maybe ask for you to share some credentials so I could work out what was needed. I did a terrible job of future proofing this particular repo for additions like for a different inverter type.

I'll see what I can do though. If you've been following all the chatter over on the repo for the HA integration you'll see that the API has become increasingly difficult to work against on account of Growatt blocking us all the time. Therefore I'm starting to steer people towards using grott instead. However, that transition is in it's infancy and doesn't yet easily support configuration such as this repo achieves.

I'll help out where I can though.

**Comment by xhemp** [comment]
Hey @muppet3000 , thanks for having a look.
Indeed, I have an SPA3000TL and it looks it's really different from the others and my understanding is that's the reason why it doesn't work as it gets info from different endpoints on Growatt's side.

My config is here:
https://pastebin.com/uVK17hbz

I do use Grott as well but when I tried to use growatt-charger was more to configure things the way I wanted instead of keep going through the ShineApp or via Web.
I also found this on one of the GH's on SJord's repo that might help on getting SPA info:

https://github.com/Sjord/growatt_api_client/issues/33

I can test and help on whatever is needed of me, unfortunately I don't know how to code so help on that front from me is very limited :)

Edit: You asked me how it shows on Growatt's website, device type shows as AC Couple.
Edit 2: Forgot to mention, I do use Grott and I love it, it would be amazing if we could send data directly to the device locally instead of to Growatt and then from Growatt to us.

**Comment by muppet3000** [comment]
Thanks for sharing that.

Assuming in the config file you're using the correct values for the `location`, `username` and `password` it should be fine. If you only have 1 inverter then there's no need to specifc the `plant_id` and `device_sn` (this may be the issue, on the other hand, it could be nothing).

The Sjord client is "yet another" api client, which given how flakey the growatt servers have become with them blocking anything that polls too regularly, I'm trying to get away from.

As for the AC Couple type, I know that the API doesn't have support for (at least the python one that myself and indy maintain(ed)). I'm reluctant to pour too much effort into it given that I think I can get configuration "pushing" working via the HA integration that I'm working on without too much trouble.
I'd much rather focus my efforts on getting all of this functionality into the Grott based HA integration and then actively supporting that, knowing that Growatt aren't about to come along and rip it away from underneath us.

I hope you can understand my position on this, the longer I spend working on non-grott stuff, the longer it takes for me to get the grott stuff (which is the future) working.

**Comment by xhemp** [comment]
No worries, @muppet3000 , I understand and agree with you 100%, no point in going through Growatt if we can do it locally!
I had luck setting stuff through the API with that post from coleburg, I will play a bit with that and see what I can do for the time being.
Thanks a million!
