### ISSUE TITLE
wh_hours -> wh_period in forecast-solar==3.0

### ISSUE THREAD

**Issue by jimwormold** [muppet3000/growatt-weather-based-charger#4]
Hi
I just rebuilt my docker image which brought in the latest forecast-solar and got errors saying that the "estimate object has no wh_hour member" - I believe this is because their new package has replaced wh_hour with wh_period instead.

Just a heads up, to either make changes or fix the version in requirements.txt to 2.3.0

Many thanks

**Comment by muppet3000** [comment]
Thanks, I'll take a look when I next get a chance. I'm still using the last one I built.
Have you fixed to the previous version or attempted to fix the code?

**Comment by jimwormold** [comment]
I just fixed to the previous version in requirements.txt

**Comment by muppet3000** [comment]
Fixed and pushed change - now on main
