### ISSUE TITLE
OpenStreetMap url format change

### ISSUE THREAD

**Issue by jimwormold** [muppet3000/growatt-weather-based-charger#5]
OpenStreetMap have changed the request url format

I think get_lat_long() needs to change from:

url = 'https://nominatim.openstreetmap.org/search/' + urllib.parse.quote(address) +'?format=json'

to

url = 'https://nominatim.openstreetmap.org/search?q=' + urllib.parse.quote(address) +'&format=json'

==============================
Screen scrape from browser:

File not found: API no longer accessible via this URL
Using the URL /search/ and /reverse/ (with slashes) is no longer supported. Please use URLs as given in the documentation.

Examples how to change the URL:

You use: https://nominatim.openstreetmap.org/search/?q=Berlin
Change to: https://nominatim.openstreetmap.org/search?q=Berlin

You use: https://nominatim.openstreetmap.org/search/US/Texas/Huston
Change to: https://nominatim.openstreetmap.org/search?q=Huston, Texas, US

See [github issue #3134](https://github.com/osm-search/Nominatim/issues/3134) for more details.

**Comment by muppet3000** [comment]
Fixed and pushed - now on main (also pushed into Docker hub)
