### ISSUE TITLE
Am I dumb?

### ISSUE THREAD

**Issue by ULtiMat3DruMa** [muppet3000/growatt-weather-based-charger#6]
Since the 4th of August I'm getting this error: 

2023-08-04 01:55:02 ERROR: Please check your configuration values also e.g. you've updated the default values
2023-08-04 01:55:02 ERROR: Expecting value: line 1 column 1 (char 0)

I've since removed the old config file and re-ran the container with a fresh .ini file which is works initially, once I enter my values I get the same issue again, What am I doing wrong?

here is my .ini:

[growatt]
#The capacity of the batteries in wh e.g. 9.9kwh
battery_capacity_wh = 12000

#The maximum charge rate the battery is capable of in w e.g. 3000w = 3kw
maximum_charge_rate_w = 3000

#The statement of charge (minimum % the battery will ever drop to)
statement_of_charge_pct = 10

#The minimum charge % that you would like to ever go down to e.g. always charge the batteries to a minimum of 45%
minimum_charge_pct = 20

#The maximum charge % that you would like to ever go up to e.g. never charge the batteries to greater than 100%
maximum_charge_pct = 100

#The average load consumption of your house in w e.g. 850w (used to calculate % charge required to get to the point where you are running purely on solar power)
average_load_w = 400

#TODO - Make these optional/via env var
#Growatt username as used in the shinephone app
#OPTIONAL - Can also be provided by an environment variable (GROWATT_USERNAME) to avoid credentials coded into this file
username = dontbeadummmy

#Growatt password as used in the shinephone app
#OPTIONAL - Can also be provided by an environment variable (GROWATT_PASSWORD) to avoid credentials coded into this file
password = comeonnow

#Growatt Plant ID to be configured - must have a device_sn provided also
#OPTIONAL - If not specified the first Plant & SN combo will be used
#plant_id =

#Growatt Device SN (for the plant ID) to be configured - must be provided as well as plant_id
#OPTIONAL - If not specified the first Plant & SN combo will be used
#device_sn =

[tariff]
#Off peak start time in 24hour clock format
off_peak_start_time = 02:00

#Off peak end time in 24 hour clock format
off_peak_end_time = 05:00

[forecast.solar]
#Your location e.g. your home address
location = nicetry

#The angle of your solar panels in degrees 0=Horizontal, 90=Vertical
declination = 30

#(360 degrees - -180=North, -90=East, 0=South, 90=West)
azimuth = -11

#The nominal power of your solar panels in kw e.g. 6.1kw
kw_power = 6.5

#Damping factor - Adjusts the results in the morning and evening
damping = 0.25

#Confidence in the returned results 0-1 e.g. 0.8 = 80% confidence in the results returned
confidence = 0.9

**Comment by muppet3000** [comment]
You are not dumb, there was a change in the upstream library that gets location data.
You don't need to change anything just pull the latest version of the code from 'main' or the latest docker image.

Let me know how you get on (see #5 for more info)

**Comment by ULtiMat3DruMa** [comment]
Thanks, apologies for my ignorance. I'll try in 24 hours. I can't login on Growatt right now, I assume too many attempts for one day. so far no error

**Comment by ULtiMat3DruMa** [comment]
Apologies but im getting the same error witht eh 'lastest' docker command.

sudo docker run --rm -e TZ=Europe/London -v ${PWD}/conf:/opt/growatt-charger/conf -v ${PWD}/output:/opt/growatt-charger/output -v ${PWD}/logs:/opt/growatt-charger/logs muppet3000/growatt-charger:latest

What do I change it to?

**Comment by muppet3000** [comment]
> Apologies but im getting the same error witht eh 'lastest' docker command.
> 
> sudo docker run --rm -e TZ=Europe/London -v ${PWD}/conf:/opt/growatt-charger/conf -v ${PWD}/output:/opt/growatt-charger/output -v ${PWD}/logs:/opt/growatt-charger/logs muppet3000/growatt-charger:latest
> 
> What do I change it to?
> 

Have you remembered to pull the latest image (`docker pull growatt-charger:latest`).

If you run `docker images` and look for the growatt-charger entry it should say that it's only a few days old

You can add `--pull=always` to your docker run command to make sure you always pull the latest if there's a new one.

**Comment by ULtiMat3DruMa** [comment]
Sorry. Yes I have now done this, I don't know docker. Thanks for the help

**Comment by muppet3000** [comment]
> Sorry. Yes I have now done this, I don't know docker. Thanks for the help

No problem, while docker is an unknown for many people it's one of the best ways to deliver projects like this. Everything is self contained, there's no need to assist people with installing dependencies and "it doesn't work for me" problems etc.

Glad you got it all sorted.
