### ISSUE TITLE
Looks like Growatt changed/ depreciated their API URL

### ISSUE THREAD

**Issue by ULtiMat3DruMa** [muppet3000/growatt-weather-based-charger#7]
I'm sure you already know about the HA integration with the same issue

But adding this issue here since its similarly affected.

Log from /opt/logs/latest 
2023-09-27 00:05:22 ERROR: Please check your configuration values also e.g. you've updated the default values
2023-09-27 00:05:22 ERROR: 405 Client Error: Not Allowed for url: https://server-api.growatt.com/newTwoLoginAPI.do

**Comment by muppet3000** [comment]
Fixed it this morning, pull the latest code/docker image.

**Comment by ULtiMat3DruMa** [comment]
Legend! although I cannot pull the latest version down says 

sudo docker pull growatt-charger:latest
Error response from daemon: pull access denied for growatt-charger, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ULtiMat3DruMa** [comment]
never mind had to do 

muppet3000/growatt-charger instead of just growatt-charger

**Comment by muppet3000** [comment]
No problem, glad it was a quick win.
I'm about to spend my evening responding to the 20,000 messages on the home assistant GitHub about the same issue, fun times.

**Comment by ULtiMat3DruMa** [comment]
I do not envy you, shame Growatt couldn't give you a heads up
